######################################################################
# Automatically generated by qmake (3.1) Wed May 29 08:07:53 2024
######################################################################

TEMPLATE = app
TARGET = Mammoth
INCLUDEPATH += .
QT += gui core widgets network
HEADERS += src/mammoth.hpp src/feed.hpp src/feedgroup.hpp src/feedtable.hpp
SOURCES += src/main.cpp src/mammoth.cpp  src/feed.cpp src/feedgroup.cpp src/feedtable.cpp
